### ISSUE TITLE
Galaxy Testnet v0.0.3-alpha-demo

### ISSUE THREAD

**Issue by guylepage3** [galaxypi/galaxy#11]
Great work on Galaxy Testnet v0.0.2-alpha-demo @faddat! 😄 

### Goal
Provide the fastest demo with the least amount of steps possible while guiding the audience through via effective communication.

### UX requirements
1. Demo'er opens Mac laptop
2. Demo'er opens Terminal window
3. Demo'er installs Galaxy Testnet  v0.0.3-alpha
4. Galaxy Testnet  v0.0.3-alpha starts syncing
5. Demo'er and audience wait for 5-10 minutes for the chain to fully sync
6. Galaxy Testnet  v0.0.3-alpha catches up to the end of the chain
7. Audience see a message "Your Galaxy Testnet Node is now caught up to the latest block"
8. Demo'er creates a new wallet
9. Demo'er sends coins to that new wallet
10. Audience see's the receiving of coins.

**Comment by faddat** [comment]
Number 7 there is a problem.  It would require some very serious digging around, and even then it would only be on the screen for a split second (literally a split second.)

**Comment by faddat** [comment]
So the next thing is Number 3 on that list...

So, we should be going from no-galaxy, to a full galaxy setup?

That is, instead of having galaxy already installed on the laptop when the demo starts.  This could help with Syncing, too.  We can't really guarantee that it will take 5-10 minutes.  It's a lot easier to guarantee that sync will take <1 minute than it is to ensure it takes 5-10 minutes.

**Comment by faddat** [comment]
Almost all but not #7.  

I'm going to start with the install script and move forward from there.  Im still not convinced the demo should include the installation.

**Comment by faddat** [comment]
Script enhanced.  

Now checking if sync time is improved by syncing from a 64 bit machine.

**Comment by faddat** [comment]
curl https://raw.githubusercontent.com/galaxypi/galaxy/master/install-mac.sh | bash

**Comment by guylepage3** [comment]
Nice! 
```
curl https://raw.githubusercontent.com/galaxypi/galaxy/master/install-mac.sh | bash
```

**Comment by guylepage3** [comment]
Closing this issue. New deliverables for UX enhancements are here..

[Galaxy DemoCoin Testnet v0.0.4-alpha-demo UX enhancements](https://github.com/galaxypi/galaxy/issues/21)
