### ISSUE TITLE
Improve UX and brand feeling in install script

### ISSUE THREAD

**Issue by vsund** [galaxypi/galaxy#18]
The current install script doesn't really make a great user experience and doesn't establish a brand feeling when installing (as e.g. Homebrew and Keybase do).

cc @guylepage3

**Comment by guylepage3** [comment]
Found a really nice layout that was easy to read for install animation..

<img width="1920" alt="screenshot 2018-07-18 17 07 08" src="https://user-images.githubusercontent.com/1711854/42939531-06488402-8b24-11e8-9eec-24773f9e8abb.png">
<img width="1920" alt="screenshot 2018-07-18 17 07 19" src="https://user-images.githubusercontent.com/1711854/42939532-065ba028-8b24-11e8-9609-438369246b29.png">

**Comment by vsund** [comment]
I'd also like to throw in https://www.youtube.com/watch?v=31XZYMjg93o, a talk analyzing `git`'s user interface, what went wrong there and how to fix it. Also mentions some methods of e.g. how to test whether something works as expected or not.

**Comment by guylepage3** [comment]
Hey @faddat @vsund...

The following is my "wishlist" / "UX recommendations" for the install script...

1. One-line installer
```
bash install galaxy
```
If not... then we will need to live with our current one-line installer.

2. Previously installed `galaxycli` and `galaxyd`
Let's change
```
This script will remove previously installed directories of galaxycli and galaxyd.
```
to
```
This script will remove previously installed directories:
- galaxycli
- galaxyd
```

3. After choosing `y`
Let's change
```
Continuing with install. Just bear with me for a moment.
```
to
```
Installing ..............................................................................................................................................
...........................................................................................................................................................................................................
```
NOTE: the periods start out one by one as a loader......... Then stop upon getting to:
```
Clearing leftovers from galaxycli and galaxyd.
```

4. Downloading and installing should be separate steps...
Change
```
Downloading and installing galaxycli and galaxyd.
```
to
```
Downloading & Installing.... galaxycli & galaxyd
###################################################################   100.0%
#####################################################                                    76.6%
```
Let's make the `#` symbols `bright green` in color please. Let me know if you need a hex color.

5. Change `Initializing galaxyd.` to `Initializing galaxyd....`

6. Change `Adding seeds to config.` to `Adding seeds to config....`

7.

**Comment by guylepage3** [comment]
7. Choose a node name
Change...
```
Now I need a name to distinguish your node from others (e.g. giantchicken or mygalaxynode).
```
to...
```
Galaxy needs to distinguish individual nodes from one another. This is accomplished by having users choose a Galaxy node name.

Example: <batpig-007>, <gopher-galaxy-node>

```
NOTE: please make the opening and closing brackets `red` in color. Let me know if you need a hex color.

**Comment by faddat** [comment]
https://misc.flogisoft.com/bash/tip_colors_and_formatting

^^ that's approximately what we have to work with in this case.  If I find another link, I will paste it here as well.

**Comment by guylepage3** [comment]
8. Genesis Block

Change
```
Fetching genesis block.
```
to
```
Initializing the Galaxy genesis block...............................
```

**Comment by guylepage3** [comment]
@faddat here's the green 
```
\e[38;5;92m
```
Here's the red
```
\e[38;5;91m
```

**Comment by faddat** [comment]
@guylepage3 

I have not added "animated" periods, since there is no wait at that point in the install.  Instead, I have outputted nothing.  I'll run through the installer when done with this batch of changes, and you can let me know how it's looking :).

**Comment by faddat** [comment]
<img width="448" alt="screen shot 2018-08-13 at 8 09 50 pm" src="https://user-images.githubusercontent.com/7142025/44064773-dea08cd6-9f34-11e8-83de-54aa856e282b.png">


Doesn't seem to be light green, but does seem to match the purple that you used on the deck.  I'm going to keep it for now.  Of course, still have to figure out how to change the color of the hash marks...

**Comment by guylepage3** [comment]
Hm.. Let's try for the `#` Light green here – https://misc.flogisoft.com/bash/tip_colors_and_formatting

**Comment by faddat** [comment]
1) One-line installer aka `bash install galaxy`-- not possible without increasing complexity because the installer needs to be installed.  Our current script fetches the installer, runs it, and allows the user to start galaxy.  

2)  This has been completed.  The script now looks like:

```
This script will remove previously installed directories:
- galaxycli
- galaxyd
```

3) For this one, I have opted to remove output altogether.  There's no actual wait at this stage.  

4) I will adjust to:

```
Downloading & Installing.... galaxycli & galaxyd

##########################################################################   100.0%
####################################################                          76.6%
```
Not certain about the #'s.  There's probably a way to color them but I haven't found it yet.  Much easier to color stuff that we're echoing.  (but I do think it's doable... just haven't figure it out yet)


5)  **Initializing Galaxyd** Dropping output here. It will no longer mention the init step.  

6)  **Adding seeds** Dropping output here.  It will no longer mention adding the seeds to the config.  

7) **Choose a node name** can totally do this one, but have not yet.  No difficulties in doing it AFAIK.  

8) **Genesis block** Dropping this, as well.  

9) **Installed**  There's an emoji in there.  I think that we can do everything except for the emoji, since I don't think there's a bash way to do that.  Bash does have some funny characters though, like a smiley-face thing (not really an emoji though), I think.  Not sure how to summon it though.  

10) **Start sync**  I can make this change, no problem.

**Comment by guylepage3** [comment]
@faddat thanks for the feedback.

Let's keep 5, 6 & 8 in as it provides a better UX as to what's going on for the user... You were right to have it in, but it just needs the adjustments. 👍

**Comment by faddat** [comment]
Beginning those changes now.

**Comment by aseoconnor** [comment]
I think there is an opportunity to have a bit more surprise and delight in here - and to play into the brand architecture // vocabulary that has been set. 

Something like:

5. Finalizing prelaunch-operations. Initiating launch of your node...

6. Adding seeds to your node

7. Please name your node (this is how we will distinguish your node) and press enter: 

8. Fetching Genesis Block. Please wait. 

9. Successful launch!

Galaxy blockchain is now installed and ready to sync. This may take a while...

Navigate into the galaxy directory. Type the following;
cd ~/galaxy

**Comment by guylepage3** [comment]
Love this @aseoconnor!

I agree... This is our best opportunity to excite developers. We really need to ensure that happens.

**Comment by guylepage3** [comment]
Ok.. I am going to update the macOS install script and implement a few new changes. I'll ping the team in Discord and let everyone know when this is ready.

**Comment by guylepage3** [comment]
Ok.. I've made improvements to the UX of the macOS install...

<img width="886" alt="screenshot 2018-08-28 19 23 07" src="https://user-images.githubusercontent.com/1711854/44756412-97314500-aaf8-11e8-90f4-6234915cd3ed.png">

**Comment by guylepage3** [comment]
@faddat I am going to open a new issue and apply these changes to the Linux install script

**Comment by guylepage3** [comment]
@aseoconnor @faddat I am closing this issue... See https://github.com/galaxypi/galaxy/issues/67
