### ISSUE TITLE
Galaxy DemoCoin Testnet v0.0.4-alpha-demo UX enhancements

### ISSUE THREAD

**Issue by guylepage3** [galaxypi/galaxy#21]
## Galaxy DemoCoin Testnet v0.0.4-alpha-demo UX enhancements

The following are the list of enhancements to be made to Galaxy DemoCoin Testnet Alpha Demo for [Sprint 3](https://github.com/orgs/galaxypi/projects/3)

- [ ] #18 Improve UX and brand feeling in install script
- [ ] #22 Ensure timeouts do not happen during Galaxy DemoCoin Demo sync
- [x] #23 Install instructions

**Comment by faddat** [comment]
Will improve the install instructions tomorrow, and coordinate with Vsund on implementing his new script for TN4.

**Comment by faddat** [comment]
Closed this issue in favor of #50
