### ISSUE TITLE
Implement semantic versioning

### ISSUE THREAD

**Issue by guylepage3** [galaxypi/galaxy#27]
Since we are an open community encouraging developers to assist in the building of the project, we should start implementing semantic versioning to our processes.

Here'a great article on how semantic versioning software standards.
https://semver.org/

**Comment by guylepage3** [comment]
@faddat how's this one coming along?

**Comment by faddat** [comment]
@guylepage3 great question!

So far I've done versioning like:

first
second
third
fourth
......

which is not correct.  So, I guess that we can resolve this issue once v0.0.5 is labeled as v0.0.5?

Should I also go back and change the release names for v0.0.1-4?

It's surely a good idea to do semantic versioning.

**Comment by guylepage3** [comment]
We should be on `Testnet v0.5.0-alpha` moving toward `Testnet v0.6.0-alpha`.
- See https://semver.org/

**Comment by guylepage3** [comment]
GitHub even provides instructions on semantic versioning now when creating releases...

<img width="818" alt="screenshot 2018-08-16 10 09 02" src="https://user-images.githubusercontent.com/1711854/44213788-84a02e80-a13c-11e8-856f-32eba955c54b.png">

**Comment by guylepage3** [comment]
Going to attempt renaming the `first` tag and then updating..

**Comment by faddat** [comment]
When I tried that, it ended pretty badly.  Good luck!

**Comment by guylepage3** [comment]
GitHub generates their own version of a "[Release](https://help.github.com/categories/releases/)" on their web interface using [`git tag`'s lightweight version](https://git-scm.com/book/en/v2/Git-Basics-Tagging#_lightweight_tags). So when updating a tag name, GitHub does not update their "Release" on their web interface.

So what we will do is we will update `v0.1.0-alpha` — `v0.3.0-alpha` today. Then we'll change `forth` to `v0.4.0-alpha` tag just before we release `v0.5.0-alpha`.

**Comment by guylepage3** [comment]
Closing issue..
