### ISSUE TITLE
Make the install script use curl or wget

### ISSUE THREAD

**Issue by vsund** [galaxypi/galaxy#31]
Would be nice to use either `curl` or `wget` depending on what's available.

**Comment by faddat** [comment]
curl seems to be most widely available.  Closing this issue in favor of curl instead of wget.  

Reasoning:

Curl is installed by default on a mac and a raspberry pi and on ubuntu linux.  Wget is not.

**Comment by guylepage3** [comment]
@faddat Don't forget to follow our issue creation instructions.

Also. Upon creating issues, we need to assign;
- Assignee(s)
- Label(s)
- Project

**Comment by vsund** [comment]
I had a `download` function in mind that uses either `curl` or `wget` (whatever is installed). I think there are distributions with `wget` pre-installed but not `curl`.
