### ISSUE TITLE
Beautiful table of contents or similar on readme.md

### ISSUE THREAD

**Issue by faddat** [galaxypi/galaxy#36]
Currently there are two "orphaned" markdown files in the repo, 

```
build.md
manualinstall.md
```

They're soon to be accompanied by two new markdown files:

```
windowsinstall.md
roadmap.md
```

could you please make a ToC or similar that shows these links in a pretty way?  Thank you very much!

**Comment by guylepage3** [comment]
Will do sir! 👍
