### ISSUE TITLE
Software Roadmap

### ISSUE THREAD

**Issue by faddat** [galaxypi/galaxy#37]
Recently it was discovered that while we all agreed on the direction we're heading in, we had a tough time expressing it from a technical standpoint.  

So, we're going to create a `roadmap.md` that clearly expresses the direction of our development efforts.

**Comment by guylepage3** [comment]
Reviewing the roadmap.. https://github.com/galaxypi/galaxy/blob/develop/roadmap.md

**Comment by guylepage3** [comment]
Test comment

**Comment by guylepage3** [comment]
Closing out this issue folks.. If we need to add to the roadmap we can create a new issue.
