### ISSUE TITLE
Make the Mac installer match the linux installer

### ISSUE THREAD

**Issue by faddat** [galaxypi/galaxy#51]
**Description**
Currently, the mac installer doesn't match the linux installer in terms of output on the user's screen.  

**Items**
1) The init command shows on the user's screen on the mac, but it's hidden on the Linux version of the script.  

This is probably a requirement for closing #18

**Comment by guylepage3** [comment]
Closing this issue as the macOS install script sets precedence over the Linux install due to the UX being perfected on macOS is easier and 80% of all installs will be on macOS during this stage of the project. https://github.com/galaxypi/galaxy/issues/67
