### ISSUE TITLE
Mac installer uses wget to fetch genesis block

### ISSUE THREAD

**Issue by faddat** [galaxypi/galaxy#53]
**Description**
The mac installer currently uses wget to fetch the genesis block.  According to #31 , we're going to "just use curl" since it is installed by default on so many platforms.  

**Items**
1) Should change the mac installer to use curl to fetch the genesis block, so that we do not stumble on a wget dependency.  

Needed for #18

**Comment by guylepage3** [comment]
@faddat Don't forget to follow our issue creation instructions.

Also. Upon creating issues, we need to assign;
- Assignee(s)
- Label(s)
- Project

**Comment by faddat** [comment]
Great catch @guylepage3 !  Assigned, and moved to an appropriate place on the kanban.
