### ISSUE TITLE
Fork Cosmos Testnet Explorer

### ISSUE THREAD

**Issue by faddat** [galaxypi/galaxy#55]
It seems like low-hanging fruit for us to implement something like:

https://explorecosmos.network/

Really it shouldn't take a whole lot more than changing:

https://github.com/cosmos/explorer  

A little bit to fit our needs.  

<img width="820" alt="screen shot 2018-08-15 at 6 17 39 pm" src="https://user-images.githubusercontent.com/7142025/44176361-8c69bf80-a0b7-11e8-89f4-a1f4ed0a9e24.png">

This should be completed before #54 is released.

**Comment by guylepage3** [comment]
@faddat I changed the title of this one to be more reflective of the task at hand... Don't forget to follow our issue creation instructions.

Also. Upon creating issues, we need to assign;
- Assignee(s)
- Label(s)
- Project

**Comment by faddat** [comment]
Assigned and labeled and project'd.  I'm also going to look into how milestones work.  Eg: For this one the milestone could be v0.0.6
